# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Gernal-L
on:
  # Schedule daily updates
  schedule: [{cron: "30 * * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  # push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:         
      - name: Gernal L
        uses: lowlighter/metrics@latest
        with:
          filename: general_L.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_gist: ${{ secrets.GIST }}
          output_action: gist
          repositories_forks: yes
          repositories_skipped: ${{ secrets.IGNORE }}
          # Options
          user: bradly0cjw
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          config_timezone: Asia/Taipei
          config_order: base.header, introduction, base.activity+community, base.repositories, lines, language, gists, isocalender, habbit , base.metadata
          plugin_gists: yes
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 1000
          plugin_habits_languages_limit: 0
          plugin_habits_languages_threshold: 0%
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: data, markup, programming, prose
          plugin_languages_colors: github
          plugin_languages_details: bytes-size, percentage, lines
          plugin_languages_indepth: yes
          plugin_languages_limit: 8
          plugin_languages_recent_categories: data, markup, programming, prose
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: recently-used
          plugin_languages_threshold: 0%
          plugin_lines: no
          plugin_traffic: yes
